### ISSUE TITLE
Provide ability to define dsc-v3 resource path (Support sxs installation)

### ISSUE THREAD

**Issue by BerheAbrha** [PowerShell/DSC#133]
### Summary of the new feature / enhancement

dscv3 is relying on system variable ($env:path) for resource discovery.  Provide an ability to specify the directory for all dscv3 resources.  
          - This will enable sxs installation possible.  (GC-Agent supports this)
          - DSC is slow locating resources since it is checking a big list of paths in $env:path.

### Proposed technical implementation details (optional)
Pass optional DSC_Resouce_Path to DSC .
_No response_

**Comment by BerheAbrha** [comment]
Overwriting the system $env:path in the process may impact locating executable or other resource dependencies that are already under $env:path

**Comment by Bpoe** [comment]
I agree with BerheAbrha. Resources called and the processes spawned calling those may depend on PATH being intact. We will need to support either specifying the search path(s) as an argument or support another ENV var that would be used if specified instead of PATH. (Think something similar to PSModulePath)

**Comment by SteveL-MSFT** [comment]
We can have a `DSC_RESOURCE_PATH` env var that, if defined, overrides any search of `PATH`.
