### ISSUE TITLE
Need a way to selectively disable individual resources/providers

### ISSUE THREAD

**Issue by anmenaga** [PowerShell/DSC#274]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

An example that I've hit with WMIGroup resource provider:
On Win11 it returns ~1300 resource types, making "dsc resource list" output useless if user is interested in other resource types.

Need a way to disable/enable specific resource types/providers (this will help with performance too).
Maybe have a config file, that can be edited by the user, that lists disabled resources.

### Expected behavior

```console
N/A
```

### Actual behavior

```console
N/A
```

### Environment data

```PowerShell
N/A
```

### Version

3.0.0-alpha.4

**Comment by michaeltlombardi** [comment]
This raises a question about being able to use a configuration file to control how `dsc` behaves - continually defining options at the prompt will get more and more user-unfriendly as the amount of options increases.

**Comment by SteveL-MSFT** [comment]
My immediate thought is to have a `--recurse` type switch to enumerate provider resources (although we'd call it something more user friendly like `--include-provider-resources`).  We might even consider if used interactive to prompt before dumping out 1300 WMI resources.

**Comment by michaeltlombardi** [comment]
I'm not _opposed_ to a flag for listing resources from providers as an opt-in flag, but it should probably be an array option, so I could specify _which_ provider resources I want enumerated.

If we consider a hypothetical where I have PSDSC, WMI, and Python providers, I might only want to list the resources for PSDSC or Python.

If we had a `--provider` option with a builtin `all` value (enumerate _everything_), that might be more wieldy.

**Comment by SteveL-MSFT** [comment]
Let's have the config discussion in https://github.com/PowerShell/DSC/issues/282 and keep this the interactive cmdline discussion.

**Comment by SteveL-MSFT** [comment]
WG discussed:

- first, we need https://github.com/PowerShell/DSC/issues/139 implemented to expose `kind`
- show `kind` as a new column after `version` and before `methods`
- by default, dsc does not perform a `list` against adapters, but shows the adapters
- a new `--adapter` parameter taking the name or wildcard and for `*` it shows everything including non-adapters or adapted resources otherwise just resources that match the adapter name
- `dsc resource list *Network* --adapter *` would search for any resources or adapted resource where the name includes `Network`, for example
